
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    networks:
      - dmlab_network
    volumes:
      - sqldata:/var/opt/mssql

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:
      - dmlab_network
    volumes:
      - .:/app

networks:
  dmlab_network:
    driver: bridge

volumes:
  sqldata: